version: '3.8'
services:
  web:
    image: 'tomcat:9.0'
    ports:
      - '8888:8080'
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "Divino!"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - 'mysql-data:/var/lib/mysql'
volumes:
  mysql-data:
    driver: 'local'
